sudo: false
language: cpp
dist: trusty

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-multilib
            - valgrind
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
    fi
  - curl https://codeload.github.com/google/googletest/tar.gz/release-1.8.0 -o release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake -DBUILD_SHARED_LIBS=ON .
  - make
  - sudo make install
  - cd ..

install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install valgrind;
    fi

before_script:
  - echo ${CC}
  - echo ${CXX}
  - ${CXX} --version
  - export TESTPREFIX="apitest"
  - cmake . && cmake --build .
  - sh install_ci_make.sh

script:
  - make CXX=${CXX} CC=${CC} DEBUGFLAGS="-ggdb" OPTFLAGS=""
  - make test_unit CXX=${CXX} CC=${CC} DEBUGFLAGS="-ggdb" OPTFLAGS=""
  - make test CXX=${CXX} CC=${CC} TESTPREFIX=${TESTPREFIX} DEBUGFLAGS="-ggdb" OPTFLAGS=""
  - if [ "$CXX" == "g++-6" ] && [ "$TRAVIS_OS_NAME" != "osx" ]; then
      make test_address CXX=${CXX} CC=${CC} DEBUGFLAGS="-ggdb" OPTFLAGS="" LDFLAGS="-pthread -latomic -fuse-ld=gold" TESTPREFIX=${TESTPREFIX} ;
    else
      make test_address CXX=${CXX} CC=${CC} DEBUGFLAGS="-ggdb" OPTFLAGS="" TESTPREFIX=${TESTPREFIX} ;
    fi
  - valgrind --track-origins=yes --leak-check=full ./${TESTPREFIX}
